name: build
description: This is an action to automate Gradle build
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - uses: actions/setup-java@v3
      with:
      distribution: 'temurin'
      java-version: '11'
      cache: 'gradle'
    
    - run: ./gradlew build
      shell: bash
