name: generate-docs
description: This is an action to generate html documentation from asciidoc files.

inputs:
  github-token:
    description: 'The GitHub token to authenticate with.'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: find_ref
      run: |
        builddocs='${{github.workspace}}/build/docs'
        versionsfile=$builddocs/versions.json

        mkdir -p $builddocs

        if [ ! -f docs/versions.json ]; then
          echo '{"versions": [{"label": "stable","checkout": "${{github.ref_name}}","latest": true}]}' > $versionsfile
        else
          jq 'if all(.versions[]; .latest != true) then .versions[0].latest = true else . end' docs/versions.json > $versionsfile
        fi

        jq -c '.versions[]' $versionsfile | while read i; do
          label=$(echo "$i" | jq -r '.label')
          checkout=$(echo "$i" | jq -r '.checkout')

          git clean -fdx
          git checkout $(git rev-parse $checkout)
          mkdir -p $builddocs/${{ inputs.label }} && cp -R ${{github.workspace}}/docs/* $builddocs/${{ inputs.label }}/
          docker run -v $builddocs/${{ inputs.label }}:/documents asciidoctor/docker-asciidoctor asciidoctor --backend=html5 -a icons=font -a setanchors=true -a sectlinks=true -a encoding=utf-8 -a linkattrs=true -a idprefix= -a toc=right -a outfilesuffix=.ahtml '**/*.adoc'
        done
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: ${{github.workspace}}/build/docs/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        exclude_assets: '**.adoc,*/versions.json'
        publish_branch: gh-pages-test
        publish_dir: ${{github.workspace}}/build/docs/
