name: generate-docs
description: This is an action to generate html documentation from asciidoc files.

inputs:
  label:
    description: 'Label for the version.'
    required: true
  ref:
    description: 'Ref to checkout.'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: find_ref
      run: |
        echo "ref=$(git rev-parse ${{ inputs.ref }})" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.find_ref.outputs.ref }}

    - run:
        mkdir -p ${{github.workspace}}/build/docs/${{ inputs.label }} && cp -R ${{github.workspace}}/docs/* ${{github.workspace}}/build/docs/${{ inputs.label }}/
      shell: bash

    - run:
        docker run -v ${{github.workspace}}/build/docs/${{ inputs.label }}:/documents asciidoctor/docker-asciidoctor asciidoctor --backend=html5 -a icons=font -a setanchors=true -a sectlinks=true -a encoding=utf-8 -a linkattrs=true -a idprefix= -a toc=right -a outfilesuffix=.ahtml '**/*.adoc'
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: ${{github.workspace}}/build/docs/
