name: generate-docs
description: This is an action to generate html documentation from asciidoc files.

runs:
  using: "composite"
  steps:
    - run:
        mkdir -R ${{github.workspace}}/build/docs && cp ${{github.workspace}}/docs ${{github.workspace}}/build/docs
      shell: bash

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - uses: gradle/gradle-build-action@v2
      with:
        arguments: run --args="${{github.workspace}}/build/docs"
        build-root-directory: ${{ github.action_path }}
