name: generate-docs
description: This is an action to generate html documentation from asciidoc files.

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - uses: gradle/gradle-build-action@v2
      with:
        arguments: run
