name: generate-docs
description: This is an action to generate Enonic Developer Portal documentation from asciidoc files.

inputs:
  github-token:
    description: 'The GitHub token to authenticate with.'
    required: true
  versions:
    description: 'Versions to generate documentation for. In JSON format.'
    required: false
  webhook-secret:
    description: 'The secret with which to generate the webhook signature hash.'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.repository.default_branch }}

    - id: Build
      run: |
        source=${{github.workspace}}
        build=${{github.action_path}}/build
        output=${{github.action_path}}/output
        versions_file=$output/versions.json

        mkdir --parents $build
        mkdir --parents $output

        if [ ! -f $source/docs/versions.json ]; then
          echo '{"versions": [{"label": "stable","checkout": "${{github.ref}}","latest": true}]}' > $versions_file
        else
          jq 'if all(.versions[]; .latest != true) then .versions[0].latest = true else . end' $source/docs/versions.json > $versions_file
        fi

        jq -c '.versions[]' $versions_file | while read i; do
          label=$(echo "$i" | jq -r '.label')
          checkout=$(echo "$i" | jq -r '.checkout')
          build_subdir="$build/$label"
          output_subdir="$output/$label"

          git clean -fdx
          git checkout $(git rev-parse $checkout)

          mkdir "$build_subdir" && cp --recursive --no-target-directory "$source" "$build_subdir"

          docker run --volume "$build_subdir:/documents" --workdir /documents/docs asciidoctor/docker-asciidoctor asciidoctor \
          --backend html5 \
          -a icons=font \
          -a setanchors=true \
          -a sectlinks=true \
          -a encoding=utf-8 \
          -a linkattrs=true \
          -a idprefix= \
          -a toc=right \
          -a outfilesuffix=.ahtml \
          '**/*.adoc'

          mkdir "$output_subdir" && cp --recursive --no-target-directory "$build_subdir/docs" "$output_subdir"
        done
      shell: bash

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        exclude_assets: '**/*.adoc,*/versions.json'
        publish_dir: ${{github.action_path}}/output
    - name: Notify
      run: |
        payload='{"repo": "${{ github.server_url }}/${{ github.repository }}"}'
        secret='${{ inputs.webhook-secret }}'

        cmd=("curl" "--fail-with-body" "-X" "POST" "-H" "Content-Type: application/json" "-d" "$payload")

        if [[ -n "$secret" ]]; then
            digest=$(echo -n "$payload" | openssl dgst -sha256 -hmac "$secret" | cut -d' ' -f2)
            cmd+=("-H" "X-Hub-Signature-256: sha256=$digest")
        fi

        cmd+=("https://developer.enonic.com/_/service/com.enonic.site.developer/documentation")

        "${cmd[@]}"
      shell: bash
