name: generate-docs
description: This is an action to generate html documentation from asciidoc files.

runs:
  using: "composite"
  steps:
    - run:
        ls -la ${{ github.action_path }}
      shell: bash
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - uses: gradle/gradle-build-action@v2
      with:
        arguments: run --args="${{github.workspace}}/docs"
        #gradle-executable: ${{ github.action_path }}/gradlew
        build-root-directory: ${{ github.action_path }}
