name: Release to Maven Central Repository

on:
  workflow_dispatch:
    inputs:
      groupId:
        description: 'Group Id'
        required: true
        type: string
      artifactId:
        description: 'Artifact Id'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string
env:
  GROUP_ID: ${{ inputs.groupId }}
  ARTIFACT_ID: ${{ inputs.artifactId }}
  VERSION: ${{ inputs.version }}
  JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
  JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
  JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
  JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
  JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}

jobs:
  release-to-central-portal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release the artifacts to Maven Central
        run: |
          cd ./jreleaser-gradle-release-lib
          ./gradlew releaseToCentralPortal \
              -P sourceGroupId=$GROUP_ID \
              -P sourceArtifactId=$ARTIFACT_ID \
              -P sourceVersion=$VERSION \
              -P jreleaserGpgPublicKey=$JRELEASER_GPG_PUBLIC_KEY \
              -P jreleaserGpgSecretKey=$JRELEASER_GPG_SECRET_KEY \
              -P jreleaserGpgPassphrase=$JRELEASER_GPG_PASSPHRASE
