name: JReleaser Gradle Plugin (XP) - Release XP to Central Portal Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
env:
  VERSION: ${{ inputs.version }}
  JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
  JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
  JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}

jobs:
  release-to-central-portal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decode GPG keys and set environment variables
        shell: bash
        run: |
          echo "${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}" | base64 --decode > pub.gpg
          echo "${{ secrets.JRELEASER_GPG_SECRET_KEY }}" | base64 --decode > sec.gpg

          echo "JRELEASER_GPG_PUBLIC_KEY=$(pwd)/pub.gpg" >> $GITHUB_ENV
          echo "JRELEASER_GPG_SECRET_KEY=$(pwd)/sec.gpg" >> $GITHUB_ENV

      - name: Release the XP artifacts to Maven Central
        run: |
          cd ./jreleaser-gradle-release-xp
          ./gradlew jreleaserDeploy -P sourceVersion=$VERSION -P jreleaserGpgPublicKey=$JRELEASER_GPG_PUBLIC_KEY -P jreleaserGpgSecretKey=$JRELEASER_GPG_SECRET_KEY -P jreleaserGpgPassphrase=$JRELEASER_GPG_PASSPHRASE -P jreleaserMavencentralUsername=$JRELEASER_MAVENCENTRAL_USERNAME -P jreleaserMavencentralPassword=$JRELEASER_MAVENCENTRAL_PASSWORD
