name: Release to Maven Central Repository

on:
  workflow_dispatch:
    inputs:
      groupId:
        description: 'Group Id'
        required: true
        type: string
      artifactId:
        description: 'Artifact Id'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string
env:
  GROUP_ID: ${{ inputs.groupId }}
  ARTIFACT_ID: ${{ inputs.artifactId }}
  VERSION: ${{ inputs.version }}
  NEXUS_USERNAME: ${{ secrets.nexusUsername }}
  NEXUS_USERNAME_PASSWORD: ${{ secrets.nexusUserPassword }}
  SIGNING_KEY_ID: ${{ secrets.signingKeyId }}
  SIGNING_PASSWORD: ${{ secrets.signingPassword }}
  SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.signingSecretKeyRingFile }}

jobs:
  publish-to-maven-central:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release the artifacts to Maven Central
        run: |
          ./publish-mvn-central/gradlew clean downloadArtifacts -P sourceGroupId=$GROUP_ID -P sourceArtifactId=$ARTIFACT_ID -P sourceVersion=$VERSION
          ./publish-mvn-central/gradlew publish -P sourceGroupId=$GROUP_ID -P sourceArtifactId=$ARTIFACT_ID -P sourceVersion=$VERSION -P signing.keyId=$SIGNING_KEY_ID -P signing.password=$SIGNING_PASSWORD -P signing.secretKeyRingFile=$SIGNING_SECRET_KEY_RING_FILE -P nexusUsername=$NEXUS_USERNAME -P nexusUserPassword=$NEXUS_USERNAME_PASSWORD
          ./publish-mvn-central/gradlew closeAndReleaseNexusStagingRepository -P nexusUsername=$NEXUS_USERNAME -P nexusUserPassword=$NEXUS_USERNAME_PASSWORD
