name: Release to Maven Central Repository

on:
  workflow_dispatch:
    inputs:
      groupId:
        description: 'Group Id'
        required: true
        type: string
      artifactId:
        description: 'Artifact Id'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string
env:
  GROUP_ID: ${{ inputs.groupId }}
  ARTIFACT_ID: ${{ inputs.artifactId }}
  VERSION: ${{ inputs.version }}
  NEXUS_USERNAME: ${{ secrets.nexusUsername }}
  NEXUS_USERNAME_PASSWORD: ${{ secrets.nexusUserPassword }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSPHRASE }}
  SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING }}

jobs:
  publish-to-maven-central:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Save secring file
        run: 'echo base64 -d "$SIGNING_SECRET_KEY_RING_FILE" > secring.gpg; ls -la'
        shell: bash
      - name: Release the artifacts to Maven Central
        run: |
          cd ./publish-mvn-central
          ./gradlew clean downloadArtifacts -P sourceGroupId=$GROUP_ID -P sourceArtifactId=$ARTIFACT_ID -P sourceVersion=$VERSION
          ./gradlew publish -P sourceGroupId=$GROUP_ID -P sourceArtifactId=$ARTIFACT_ID -P sourceVersion=$VERSION -P signing.keyId=$SIGNING_KEY_ID -P signing.password=$SIGNING_PASSWORD -P signing.secretKeyRingFile="../secring.gpg" -P nexusUsername=$NEXUS_USERNAME -P nexusUserPassword=$NEXUS_USERNAME_PASSWORD
          ./gradlew closeAndReleaseNexusStagingRepository -P nexusUsername=$NEXUS_USERNAME -P nexusUserPassword=$NEXUS_USERNAME_PASSWORD
